[2024-05-16 16:59:08,195] 97 werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8000
 * Running on http://192.168.0.127:8000
[2024-05-16 16:59:08,195] 97 werkzeug - INFO - [33mPress CTRL+C to quit[0m
[2024-05-16 16:59:09,583] 1414 app - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seaflux/MLOps/app.py", line 10, in home_page
    return render_template('form.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/flask/templating.py", line 151, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/flask/templating.py", line 132, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/seaflux/MLOps/templates/form.html", line 3, in top-level template code
    <form action="{{url_for('predict_datapoint')}}" method="POST">
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/flask/app.py", line 1697, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/flask/app.py", line 1686, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'predict_datapoint'. Did you mean 'static' instead?
[2024-05-16 16:59:09,588] 97 werkzeug - INFO - 127.0.0.1 - - [16/May/2024 16:59:09] "[35m[1mGET / HTTP/1.1[0m" 500 -
[2024-05-16 16:59:10,402] 1414 app - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seaflux/MLOps/app.py", line 10, in home_page
    return render_template('form.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/flask/templating.py", line 151, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/flask/templating.py", line 132, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/seaflux/MLOps/templates/form.html", line 3, in top-level template code
    <form action="{{url_for('predict_datapoint')}}" method="POST">
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/flask/app.py", line 1697, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/flask/app.py", line 1686, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'predict_datapoint'. Did you mean 'static' instead?
[2024-05-16 16:59:10,404] 97 werkzeug - INFO - 127.0.0.1 - - [16/May/2024 16:59:10] "[35m[1mGET / HTTP/1.1[0m" 500 -
[2024-05-16 16:59:10,591] 1414 app - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seaflux/MLOps/app.py", line 10, in home_page
    return render_template('form.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/flask/templating.py", line 151, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/flask/templating.py", line 132, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/seaflux/MLOps/templates/form.html", line 3, in top-level template code
    <form action="{{url_for('predict_datapoint')}}" method="POST">
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/flask/app.py", line 1697, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/flask/app.py", line 1686, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'predict_datapoint'. Did you mean 'static' instead?
[2024-05-16 16:59:10,594] 97 werkzeug - INFO - 127.0.0.1 - - [16/May/2024 16:59:10] "[35m[1mGET / HTTP/1.1[0m" 500 -
[2024-05-16 16:59:11,547] 1414 app - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seaflux/MLOps/app.py", line 10, in home_page
    return render_template('form.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/flask/templating.py", line 151, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/flask/templating.py", line 132, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/seaflux/MLOps/templates/form.html", line 3, in top-level template code
    <form action="{{url_for('predict_datapoint')}}" method="POST">
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/flask/app.py", line 1697, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/flask/app.py", line 1686, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'predict_datapoint'. Did you mean 'static' instead?
[2024-05-16 16:59:11,550] 97 werkzeug - INFO - 127.0.0.1 - - [16/May/2024 16:59:11] "[35m[1mGET / HTTP/1.1[0m" 500 -
[2024-05-16 17:01:13,469] 1414 app - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seaflux/MLOps/app.py", line 10, in home_page
    return render_template('index.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/flask/templating.py", line 151, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/flask/templating.py", line 132, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/seaflux/MLOps/templates/form.html", line 3, in top-level template code
    <form action="{{url_for('predict_datapoint')}}" method="POST">
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/flask/app.py", line 1697, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/flask/app.py", line 1686, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'predict_datapoint'. Did you mean 'static' instead?
[2024-05-16 17:01:13,472] 97 werkzeug - INFO - 127.0.0.1 - - [16/May/2024 17:01:13] "[35m[1mGET / HTTP/1.1[0m" 500 -
[2024-05-16 17:01:13,929] 1414 app - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seaflux/MLOps/app.py", line 10, in home_page
    return render_template('index.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/flask/templating.py", line 151, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/flask/templating.py", line 132, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/seaflux/MLOps/templates/form.html", line 3, in top-level template code
    <form action="{{url_for('predict_datapoint')}}" method="POST">
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/flask/app.py", line 1697, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/flask/app.py", line 1686, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'predict_datapoint'. Did you mean 'static' instead?
[2024-05-16 17:01:13,931] 97 werkzeug - INFO - 127.0.0.1 - - [16/May/2024 17:01:13] "[35m[1mGET / HTTP/1.1[0m" 500 -
[2024-05-16 17:01:14,532] 1414 app - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seaflux/MLOps/app.py", line 10, in home_page
    return render_template('index.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/flask/templating.py", line 151, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/flask/templating.py", line 132, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/seaflux/MLOps/templates/form.html", line 3, in top-level template code
    <form action="{{url_for('predict_datapoint')}}" method="POST">
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/flask/app.py", line 1697, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/flask/app.py", line 1686, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seaflux/MLOps/env/lib/python3.11/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'predict_datapoint'. Did you mean 'static' instead?
[2024-05-16 17:01:14,535] 97 werkzeug - INFO - 127.0.0.1 - - [16/May/2024 17:01:14] "[35m[1mGET / HTTP/1.1[0m" 500 -
[2024-05-16 17:01:24,331] 97 werkzeug - INFO - 127.0.0.1 - - [16/May/2024 17:01:24] "[33mGET /predict HTTP/1.1[0m" 404 -
